
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='django-kanban-board',
    version='0.0.1',
    description='Package providing models and views for displaying customizable kanban-like boards',
    python_requires='==3.*,>=3.6.0',
    project_urls={"homepage": "https://github.com/Zeerooth/django-kanban-board", "repository": "https://github.com/Zeerooth/django-kanban-board"},
    author='Radosław Stępień',
    author_email='rstepien@protonmail.com',
    license='BSD',
    keywords='django',
    packages=['kanban_board'],
    package_dir={"": "."},
    package_data={},
    install_requires=['django>=2.0', 'toml==0.*,>=0.9.0'],
    extras_require={"dev": ["bandit==1.*,>=1.6.2", "dephell==0.*,>=0.8.3", "mypy==0.*,>=0.782.0", "pylint==2.*,>=2.5.3", "pytest==3.*,>=3.0.0", "pytest-cov==2.*,>=2.4.0"]},
)
