# Generated by Django 3.0.9 on 2020-08-23 02:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='KanbanBoardName')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanBoardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='KanbanBoardStateName')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanBoardElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kanban_board_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_board.KanbanBoard')),
                ('kanban_board_state', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban_board.KanbanBoardState')),
            ],
        ),
        migrations.AddField(
            model_name='kanbanboard',
            name='states',
            field=models.ManyToManyField(to='kanban_board.KanbanBoardState'),
        ),
    ]
