# Generated by Django 3.0.9 on 2020-08-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('department', models.CharField(choices=[('management', 'Management'), ('sales', 'Sales'), ('technical', 'Technical')], max_length=255, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('kanbanboardelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kanban_board.KanbanBoardElement')),
                ('name', models.CharField(max_length=65535, verbose_name='TaskName')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to='test_project.Person')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='test_project.Person')),
            ],
            bases=('kanban_board.kanbanboardelement',),
        ),
    ]
